### ISSUE TITLE
setup.py does not install aegea or awscli-cwlogs

### ISSUE THREAD

**Issue by brymerr921** [czbiohub/utilities#33]
Hi, I followed the "Install" instructions in the README but two dependencies were not installed. After running `python setup.py install` I had to do the following:

```
conda install -y -c conda-forge awscli-cwlogs
pip install aegea
```

After this, things worked normally.

**Comment by jamestwebber** [comment]
Sorry, completely failed to see this issue until now.

This behavior is on purpose but was poorly documented: the `evros` script is an "extra"  in `setup.py` that has additional dependencies. This was so that the utilities package can be installed without `aegea`, because I use some of the functions here in other projects.

I've updated the README to clarify things.
